import { Inter } from 'next/font/google'
import '../styles/globals.css'
import Navigation from './components/Navigation'
import Script from 'next/script'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default: 'Homepage | Henry Price',
    template: '%s | Henry Price',
  },
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <Script src={`https://www.googletagmanager.com/gtm.js?id=GTM-K6BFSLDH`} />
      <body>
          <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-K6BFSLDH"
          height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
      <Navigation />
      {children}
      </body>
    </html>
  )
}
