import { Inter } from 'next/font/google'
import '../styles/globals.css'
import Navigation from './components/Navigation'
import Script from 'next/script'
import Head from 'next/head'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: {
    default: 'Homepage | Henry Price',
    template: '%s | Henry Price',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <Script strategy="afterInteractive" src="https://www.googletagmanager.com/gtag/js?id=GTM-WC424DM" ></Script>
      </Head>
      <body className={inter.className}>
      <Navigation />
      {children}
      </body>
    </html>
  )
}
